name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  markdown:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: A job to lint Markdown files
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint changelog file
        uses: avto-dev/markdown-lint@v1
        #with:
          #rules: '/lint/rules/changelog.js'
          #config: '/lint/config/changelog.yml'
          #args: './CHANGELOG.md'
        
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Lint Fixes
          commit_user_name: Lint