---
name: Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  markdown:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: Markdown Lint
    steps:
    - uses: actions/checkout@v2
    
    - name: Linting Markdown Files
      uses: articulate/actions-markdownlint@v1

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Markdown Lint
